[package]
name = "file-wrangler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.25"
serde = "1.0.188"
serde_derive = "1.0.188"
zip = "0.6.6"
toml = "0.5.11"
