[package]
name = "battery-thinkpad"
version = "0.1.0"
authors = ["leventarican <levent@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
battery = "0.7.8"